services:
  webchat-lineoa:
    build:
      context: .
      dockerfile: Dockerfile

    image: webchat-lineoa

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    command: npm run start:dev
